#!/usr/bin/env bash
set -e

# Link dotfiles
DOTFILES=( .profile .tmux.conf .zsh_aliases .zshrc )
CONFIG_REPO=~/.config-repo

for file in "${DOTFILES[@]}"; do
  ln -sf "${CONFIG_REPO}/${file}" ~/"${file}"
  echo "Linked: ${file}"
done

# Config files inside ~/.config/
CONFIG_ITEMS=( ghostty starship.toml nvim )

for item in "${CONFIG_ITEMS[@]}"; do
  ln -sf "${CONFIG_REPO}/.config/${item}" ~/.config/"${item}"
  echo "Linked: ~/.config/${item}"
done

echo "Installed"
