vim.keymap.set("n", "<leader>gs", vim.cmd.Git)
vim.keymap.set("n", "<leader>gd", function()
  vim.cmd.Git("diff")
end)
vim.keymap.set("n", "<leader>gl", function()
  vim.cmd.Git("log --stat")
end)
vim.keymap.set("n", "<leader>gc", function()
  vim.cmd.Git("commit -v -a")
end)
vim.keymap.set("n", "<leader>gp", function()
  vim.cmd.Git("push")
end)
